package game

SCREEN_WIDTH  :: 640
SCREEN_HEIGHT :: 360
TILE_SIZE     :: 16
TARGET_FPS    :: 60

PLAYER_SPEED   :: 120.0
GRAVITY        :: 500.0
JUMP_VELOCITY  :: -220.0
MAX_FALL_SPEED :: 400.0
MAX_JUMPS      :: 2

PLAYER_HITBOX_W :: 8
PLAYER_HITBOX_H :: 14

SPRITE_SRC_SIZE :: 16
SPRITE_DST_SIZE :: 16

ANIM_FRAME_TIME :: 0.172

DASH_SPEED         :: 800.0
DASH_DURATION      :: 0.15
DASH_COOLDOWN      :: 0.5
MAX_DASH_PARTICLES :: 64

DASH_DOWN_SPEED    :: 900.0
DASH_IMPACT_SIZE   :: 32
DASH_IMPACT_DAMAGE :: 36.0
DASH_IMPACT_FPS    :: 18.0

SCREENSHAKE_DURATION  :: 0.1
SCREENSHAKE_MAGNITUDE :: 1.5

QUICK_ATTACK_SRC_SIZE     :: 32
QUICK_ATTACK_FPS          :: 12.0
QUICK_ATTACK_DAMAGE_1     :: 8.0
QUICK_ATTACK_DAMAGE_2     :: 16.0
QUICK_ATTACK_COOLDOWN     :: 0.0
QUICK_ATTACK_CHAIN_WINDOW :: 3
QUICK_ATTACK_HIT_FRAME    :: 3

DOUBLE_STRIKE_CHANCE :: 0.13

WATERBLADE_SRC_SIZE     :: 32
WATERBLADE_IDLE_FPS     :: 8.0
WATERBLADE_ATTACK_FPS   :: 12.0
WATERBLADE_DAMAGE       :: 30.0
WATERBLADE_CRIT_CHANCE  :: 0.04
WATERBLADE_STAMINA_COST :: 10.0
WATERBLADE_HIT_FRAME    :: 4
WATERBLADE_OFFSET_X     :: 14.0
WATERBLADE_OFFSET_Y     :: 0.0  // nudge from player-sprite center, positive = up

WATERORB_SRC_SIZE        :: 32
WATERORB_SPAWN_FPS       :: 12.0
WATERORB_ATTACK_FPS      :: 12.0
WATERORB_DAMAGE          :: 40.0
WATERORB_SLOW_CHANCE     :: 0.20
WATERORB_SPEED           :: 90.0
WATERORB_FLIGHT_DURATION :: 1.6

WHALE_SRC_SIZE     :: 32
WHALE_HITBOX_SIZE  :: 32
WHALE_FPS          :: 18.0
WHALE_STAMINA_COST :: 55.0

SLUDGE_SLOW_DURATION :: 2.0
SLUDGE_SLOW_FACTOR   :: 0.5

PROJECTILE_RANGE            :: 90.0
PROJECTILE_DAMAGE           :: 9.0
PROJECTILE_OUT_DURATION     :: 0.45
PROJECTILE_RETURN_MAX_SPEED :: 360.0
PROJECTILE_RETURN_ACCEL     :: 0.22
PROJECTILE_SRC_SIZE         :: 8
PROJECTILE_ANIM_FPS         :: 14.0
PROJECTILE_RETURN_STOP_DIST :: 4.0

PLAYER_MAX_HP          :: 100.0
PLAYER_MAX_STAMINA     :: 50.0
PLAYER_INVULN_DURATION :: 0.6
DAMAGE_FLASH_DURATION  :: 0.1

DASH_STAMINA_COST  :: 5.0
STAMINA_REGEN_RATE :: 5.0

CRIT_DAMAGE_MULTIPLIER :: 4.0


SLUDGE_SRC_SIZE           :: 16
SLUDGE_HITBOX_W           :: 14
SLUDGE_HITBOX_H           :: 14
SLUDGE_HP                 :: 30.0
SLUDGE_DAMAGE             :: 16.0
SLUDGE_SPEED              :: 80.0
SLUDGE_ATTACK_COOLDOWN    :: 3.0
SLUDGE_ANIM_FPS           :: 10.0
SLUDGE_DEATH_DURATION     :: 0.3
SLUDGE_STAGGER_DURATION   :: 0.15
SLUDGE_STAGGER_KNOCKBACK  :: 120.0
MAX_SLUDGE_SLOTS          :: 18
MAX_SLUDGE_ALIVE          :: 8

SOLDIER_SRC_SIZE          :: 16
SOLDIER_HITBOX_W          :: 12
SOLDIER_HITBOX_H          :: 14
SOLDIER_HP                :: 40.0
SOLDIER_SPEED             :: 50.0
SOLDIER_ANIM_FPS          :: 10.0
SOLDIER_DEATH_DURATION    :: 0.3
SOLDIER_ATTACK_COOLDOWN   :: 2.2
SOLDIER_RANGE_MIN         :: 80.0
SOLDIER_RANGE_MAX         :: 150.0
SOLDIER_RANGE_HYSTERESIS  :: 8.0
SOLDIER_FIRE_FRAME        :: 2
SOLDIER_PROJECTILE_SPEED  :: 220.0
SOLDIER_PROJECTILE_DAMAGE :: 21.0
SOLDIER_PROJECTILE_SRC_SIZE :: 8
SOLDIER_PROJECTILE_MAX_DIST :: 320.0
SOLDIER_PROJECTILE_ANIM_FPS :: 12.0
SOLDIER_STAGGER_DURATION  :: 0.15
SOLDIER_STAGGER_KNOCKBACK :: 90.0
MAX_SOLDIER_SLOTS         :: 12
MAX_SOLDIER_ALIVE         :: 4
SOLDIER_WAVE_THRESHOLD    :: 3

LEVEL_MAP_PATH :: "assets/maps/lvl1.map"

PARALLAX_LAYER_COUNT :: 3
PARALLAX_SPEEDS : [PARALLAX_LAYER_COUNT]f32 : {0.05, 0.20, 0.50}

MUSIC_BASE_VOLUME :: 0.2
VOLUME_STEP       :: 0.10

// Animation Speeds
IDLE_OFFSET :: 0.04 // Idle animations look more natural when slower than others

PLAYER_IDLE_ANIM_SPEED :: ANIM_FRAME_TIME + IDLE_OFFSET