package game

SCREEN_WIDTH  :: 640
SCREEN_HEIGHT :: 360
TILE_SIZE     :: 16
TARGET_FPS    :: 60

PLAYER_SPEED   :: 120.0
GRAVITY        :: 500.0
JUMP_VELOCITY  :: -220.0
MAX_FALL_SPEED :: 400.0
MAX_JUMPS      :: 2

PLAYER_HITBOX_W :: 8
PLAYER_HITBOX_H :: 14

SPRITE_SRC_SIZE :: 16
SPRITE_DST_SIZE :: 16

ANIM_FRAME_TIME :: 0.172

DASH_SPEED         :: 800.0
DASH_DURATION      :: 0.15
DASH_COOLDOWN      :: 0.5
MAX_DASH_PARTICLES :: 64

DASH_DOWN_SPEED    :: 900.0
DASH_IMPACT_SIZE   :: 32
DASH_IMPACT_DAMAGE :: 36.0
DASH_IMPACT_FPS    :: 18.0

SCREENSHAKE_DURATION  :: 0.1
SCREENSHAKE_MAGNITUDE :: 1.5

PROJECTILE_RANGE            :: 90.0
PROJECTILE_DAMAGE           :: 9.0
PROJECTILE_OUT_DURATION     :: 0.45
PROJECTILE_RETURN_MAX_SPEED :: 360.0
PROJECTILE_RETURN_ACCEL     :: 0.22
PROJECTILE_SRC_SIZE         :: 8
PROJECTILE_ANIM_FPS         :: 14.0
PROJECTILE_RETURN_STOP_DIST :: 4.0

PLAYER_MAX_HP          :: 100.0
PLAYER_INVULN_DURATION :: 0.6
DAMAGE_FLASH_DURATION  :: 0.1


SLUDGE_SRC_SIZE        :: 16
SLUDGE_HITBOX_W        :: 12
SLUDGE_HITBOX_H        :: 12
SLUDGE_HP              :: 30.0
SLUDGE_DAMAGE          :: 16.0
SLUDGE_SPEED           :: 130.0
SLUDGE_ATTACK_COOLDOWN :: 3.0
SLUDGE_ANIM_FPS        :: 10.0
SLUDGE_DEATH_DURATION  :: 0.3
MAX_SLUDGE_SLOTS       :: 18
MAX_SLUDGE_ALIVE       :: 8

LEVEL_MAP_PATH :: "assets/maps/lvl1.map"

// Animation Speeds
IDLE_OFFSET :: 0.04 // Idle animations look more natural when slower than others

PLAYER_IDLE_ANIM_SPEED :: ANIM_FRAME_TIME + IDLE_OFFSET